#!/usr/bin/env php
<?php

$env = getopt('e:');

$config = require_once("config.php");

if ($env["e"] == 'production') {

    $config_env = require_once("config.production.php");
    $out = array_merge($config, $config_env);

    print json_encode($out);

    exit();

}

print json_encode($config);
